/nologo
/optimize+
/debug-
/unsafe-
/warn:0
/out:c:/builds/mindpowered/logic/persistence/build/vcs/csharp/bin/persistence.dll
/target:library
/reference:c:/builds/mindpowered/logic/persistence/build/vcs/csharp/bin/maglev.dll
src\persistence\Persistence.cs
src\EnumValue.cs
src\Type.cs
src\UInt.cs