// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence : global::haxe.lang.HxObject {
		
		static Persistence() {
			unchecked{
				#line 12 "/my-component/src/persistence/Persistence.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{5144726, 5541879, 13816588, 117802505, 199770554, 263824376, 907774356, 1069478790, 1314583562, 1429011148, 1533285388, 1575652104, 1776607685, 1860196033}, new string[]{"get", "obj", "SuppressWarnings", "update", "mapResults", "convertToMagLev", "convertToHaxe", "mutate", "calcKey", "mapQuery", "addGetter", "query", "mapUpdate", "addMutator"});
				#line 12 "/my-component/src/persistence/Persistence.hx"
				{
					#line 12 "/my-component/src/persistence/Persistence.hx"
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						object __temp_odecl1 = new global::haxe.lang.DynamicObject(new int[]{13816588}, new object[]{new global::Array<object>(new object[]{new global::Array<object>(new object[]{"checkstyle:FieldDocComment", "checkstyle:LocalVariableName", "checkstyle:MultipleStringLiterals", "checkstyle:MagicNumber"})})}, new int[]{}, new double[]{});
						#line 12 "/my-component/src/persistence/Persistence.hx"
						global::persistence.Persistence.__meta__ = new global::haxe.lang.DynamicObject(new int[]{5541879}, new object[]{__temp_odecl1}, new int[]{}, new double[]{});
					}
					
				}
				
			}
		}
		#line default
		
		public Persistence(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Persistence(global::maglev.MagLev bus) {
			#line 18 "/my-component/src/persistence/Persistence.hx"
			global::persistence.Persistence.__hx_ctor_persistence_Persistence(this, bus);
		}
		#line default
		
		protected static void __hx_ctor_persistence_Persistence(global::persistence.Persistence __hx_this, global::maglev.MagLev bus) {
			#line 18 "/my-component/src/persistence/Persistence.hx"
			global::persistence.Persistence _gthis = __hx_this;
			__hx_this.mutators = new global::haxe.ds.StringMap<object>();
			#line 20 "/my-component/src/persistence/Persistence.hx"
			__hx_this.getters = new global::haxe.ds.StringMap<object>();
			__hx_this.maglev = bus;
			#line 22 "/my-component/src/persistence/Persistence.hx"
			__hx_this.maglev.register("Persistence.AddMutator", global::maglev.MagLevFunction.fromFunction(new global::persistence.Persistence___hx_ctor_persistence_Persistence_22__Fun(_gthis)));
			#line 37 "/my-component/src/persistence/Persistence.hx"
			__hx_this.maglev.register("Persistence.AddGetter", global::maglev.MagLevFunction.fromFunction(new global::persistence.Persistence___hx_ctor_persistence_Persistence_37__Fun(_gthis)));
			#line 56 "/my-component/src/persistence/Persistence.hx"
			__hx_this.maglev.register("Persistence.Mutate", global::maglev.MagLevFunction.fromFunction(new global::persistence.Persistence___hx_ctor_persistence_Persistence_56__Fun(_gthis)));
			#line 66 "/my-component/src/persistence/Persistence.hx"
			__hx_this.maglev.register("Persistence.Get", global::maglev.MagLevFunction.fromFunction(new global::persistence.Persistence___hx_ctor_persistence_Persistence_66__Fun(_gthis)));
		}
		#line default
		
		public static object __meta__;
		
		public global::haxe.ds.StringMap<object> mutators;
		
		public global::haxe.ds.StringMap<object> getters;
		
		public global::maglev.MagLev maglev;
		
		public virtual void addMutator(string recordType, string operationName, object strategyMethod, object updateMapper, global::haxe.lang.Null<bool> useRecordDataAsParams) {
			#line 79 "/my-component/src/persistence/Persistence.hx"
			if (( updateMapper == null )) {
				#line 80 "/my-component/src/persistence/Persistence.hx"
				updateMapper = ((object) (( (( global::persistence.Persistence_addMutator_80__Fun.__hx_current != null )) ? (global::persistence.Persistence_addMutator_80__Fun.__hx_current) : (global::persistence.Persistence_addMutator_80__Fun.__hx_current = ((global::persistence.Persistence_addMutator_80__Fun) (new global::persistence.Persistence_addMutator_80__Fun()) )) )) );
			}
			
			#line 82 "/my-component/src/persistence/Persistence.hx"
			if ( ! (useRecordDataAsParams.hasValue) ) {
				#line 83 "/my-component/src/persistence/Persistence.hx"
				useRecordDataAsParams = new global::haxe.lang.Null<bool>(false, true);
			}
			
			#line 85 "/my-component/src/persistence/Persistence.hx"
			global::persistence._Persistence.Mutator mutator = new global::persistence._Persistence.Mutator(recordType, strategyMethod, updateMapper, (useRecordDataAsParams).@value);
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.mutators) )) ))) ).@set(this.calcKey(recordType, operationName), mutator);
		}
		#line default
		
		public virtual void addGetter(string recordType, string operationName, object strategyMethod, object queryMapper, object resultMapper, global::haxe.lang.Null<bool> useQueryValuesAsParams) {
			#line 90 "/my-component/src/persistence/Persistence.hx"
			if (( queryMapper == null )) {
				#line 91 "/my-component/src/persistence/Persistence.hx"
				queryMapper = ((object) (( (( global::persistence.Persistence_addGetter_91__Fun.__hx_current != null )) ? (global::persistence.Persistence_addGetter_91__Fun.__hx_current) : (global::persistence.Persistence_addGetter_91__Fun.__hx_current = ((global::persistence.Persistence_addGetter_91__Fun) (new global::persistence.Persistence_addGetter_91__Fun()) )) )) );
			}
			
			#line 93 "/my-component/src/persistence/Persistence.hx"
			if (( resultMapper == null )) {
				#line 94 "/my-component/src/persistence/Persistence.hx"
				resultMapper = ((object) (( (( global::persistence.Persistence_addGetter_94__Fun.__hx_current != null )) ? (global::persistence.Persistence_addGetter_94__Fun.__hx_current) : (global::persistence.Persistence_addGetter_94__Fun.__hx_current = ((global::persistence.Persistence_addGetter_94__Fun) (new global::persistence.Persistence_addGetter_94__Fun()) )) )) );
			}
			
			#line 96 "/my-component/src/persistence/Persistence.hx"
			if ( ! (useQueryValuesAsParams.hasValue) ) {
				#line 97 "/my-component/src/persistence/Persistence.hx"
				useQueryValuesAsParams = new global::haxe.lang.Null<bool>(false, true);
			}
			
			#line 99 "/my-component/src/persistence/Persistence.hx"
			global::persistence._Persistence.Getter getter = new global::persistence._Persistence.Getter(recordType, strategyMethod, queryMapper, resultMapper, (useQueryValuesAsParams).@value);
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.getters) )) ))) ).@set(this.calcKey(recordType, operationName), getter);
		}
		#line default
		
		public virtual void mutate(string recordType, string operationName, object recordData, global::haxe.lang.Function callback) {
			#line 103 "/my-component/src/persistence/Persistence.hx"
			global::persistence.Persistence _gthis = this;
			#line 106 "/my-component/src/persistence/Persistence.hx"
			if (((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.mutators) )) ))) ).exists(this.calcKey(recordType, operationName))) {
				#line 107 "/my-component/src/persistence/Persistence.hx"
				global::persistence._Persistence.Mutator mutator = ((global::persistence._Persistence.Mutator) ((((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.mutators) )) ))) ).@get(this.calcKey(recordType, operationName))).@value) );
				this.mapUpdate(mutator, recordData, new global::persistence.Persistence_mutate_108__Fun(mutator, callback, _gthis));
			}
			else {
				#line 115 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("the specified mutator has not been added")) );
			}
			
		}
		#line default
		
		public virtual void @get(string recordType, string operationName, object queryValues, global::haxe.lang.Function callback) {
			#line 119 "/my-component/src/persistence/Persistence.hx"
			global::persistence.Persistence _gthis = this;
			if (((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.getters) )) ))) ).exists(this.calcKey(recordType, operationName))) {
				#line 121 "/my-component/src/persistence/Persistence.hx"
				global::persistence._Persistence.Getter getter = ((global::persistence._Persistence.Getter) ((((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.getters) )) ))) ).@get(this.calcKey(recordType, operationName))).@value) );
				#line 123 "/my-component/src/persistence/Persistence.hx"
				this.mapQuery(getter, queryValues, new global::persistence.Persistence_get_123__Fun(getter, callback, _gthis));
			}
			else {
				#line 132 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("the specified getter has not been added")) );
			}
			
		}
		#line default
		
		public virtual string calcKey(string recordType, string operationName) {
			#line 137 "/my-component/src/persistence/Persistence.hx"
			return global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(recordType, "."), operationName);
		}
		#line default
		
		public virtual object convertToHaxe(global::maglev.MagLevAny x) {
			#line 141 "/my-component/src/persistence/Persistence.hx"
			return global::persistence.MagLevConverter.convertToHaxe(x);
		}
		#line default
		
		public virtual global::maglev.MagLevAny convertToMagLev(object x) {
			#line 145 "/my-component/src/persistence/Persistence.hx"
			return global::persistence.MagLevConverter.convertToMagLev(x);
		}
		#line default
		
		public virtual void mapUpdate(global::persistence._Persistence.Mutator mutator, object recordData, global::haxe.lang.Function callback) {
			#line 148 "/my-component/src/persistence/Persistence.hx"
			global::persistence.Persistence _gthis = this;
			#line 150 "/my-component/src/persistence/Persistence.hx"
			if (( ((object) (mutator.updateMapper) ) is global::haxe.lang.Function )) {
				#line 151 "/my-component/src/persistence/Persistence.hx"
				global::haxe.lang.Function updateMapper = ((global::haxe.lang.Function) (((object) (mutator.updateMapper) )) );
				updateMapper.__hx_invoke2_o(default(double), recordData, default(double), new global::persistence.Persistence_mapUpdate_152__Fun(callback));
			}
			else if (global::Std.isOfType(((object) (mutator.updateMapper) ), ((object) (typeof(string)) ))) {
				#line 157 "/my-component/src/persistence/Persistence.hx"
				string updateMapper1 = global::haxe.lang.Runtime.toString(((object) (mutator.updateMapper) ));
				#line 159 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevResult ret = this.maglev.call(updateMapper1, ((global::maglev.MagLevArray) (this.convertToMagLev(((object) (new global::Array<object>(new object[]{recordData})) ))) ));
				ret.onError(( (( global::persistence.Persistence_mapUpdate_160__Fun.__hx_current != null )) ? (global::persistence.Persistence_mapUpdate_160__Fun.__hx_current) : (global::persistence.Persistence_mapUpdate_160__Fun.__hx_current = ((global::persistence.Persistence_mapUpdate_160__Fun) (new global::persistence.Persistence_mapUpdate_160__Fun()) )) ));
				#line 163 "/my-component/src/persistence/Persistence.hx"
				ret.onResult(new global::persistence.Persistence_mapUpdate_163__Fun(callback, _gthis));
			}
			else {
				#line 169 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("updateMapper must be a string or function")) );
			}
			
		}
		#line default
		
		public virtual void update(global::persistence._Persistence.Mutator mutator, object recordData, global::haxe.lang.Function callback) {
			#line 173 "/my-component/src/persistence/Persistence.hx"
			global::persistence.Persistence _gthis = this;
			#line 175 "/my-component/src/persistence/Persistence.hx"
			if (( ((object) (mutator.strategyMethod) ) is global::haxe.lang.Function )) {
				#line 176 "/my-component/src/persistence/Persistence.hx"
				global::haxe.lang.Function strategyMethod = ((global::haxe.lang.Function) (((object) (mutator.strategyMethod) )) );
				strategyMethod.__hx_invoke2_o(default(double), recordData, default(double), new global::persistence.Persistence_update_177__Fun(callback));
			}
			else if (global::Std.isOfType(((object) (mutator.strategyMethod) ), ((object) (typeof(string)) ))) {
				#line 182 "/my-component/src/persistence/Persistence.hx"
				string strategyMethod1 = global::haxe.lang.Runtime.toString(((object) (mutator.strategyMethod) ));
				global::maglev.MagLevResult raw_maglev_result = null;
				#line 184 "/my-component/src/persistence/Persistence.hx"
				if (mutator.useRecordDataAsParams) {
					#line 185 "/my-component/src/persistence/Persistence.hx"
					raw_maglev_result = this.maglev.call(strategyMethod1, ((global::maglev.MagLevArray) (this.convertToMagLev(recordData)) ));
				}
				else {
					#line 187 "/my-component/src/persistence/Persistence.hx"
					raw_maglev_result = this.maglev.call(strategyMethod1, ((global::maglev.MagLevArray) (this.convertToMagLev(((object) (new global::Array<object>(new object[]{recordData})) ))) ));
				}
				
				#line 189 "/my-component/src/persistence/Persistence.hx"
				raw_maglev_result.onError(( (( global::persistence.Persistence_update_189__Fun.__hx_current != null )) ? (global::persistence.Persistence_update_189__Fun.__hx_current) : (global::persistence.Persistence_update_189__Fun.__hx_current = ((global::persistence.Persistence_update_189__Fun) (new global::persistence.Persistence_update_189__Fun()) )) ));
				#line 192 "/my-component/src/persistence/Persistence.hx"
				raw_maglev_result.onResult(new global::persistence.Persistence_update_192__Fun(callback, _gthis));
			}
			else {
				#line 198 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("strategyMethod must be a string or function")) );
			}
			
		}
		#line default
		
		public virtual void mapQuery(global::persistence._Persistence.Getter getter, object queryValues, global::haxe.lang.Function callback) {
			#line 202 "/my-component/src/persistence/Persistence.hx"
			global::persistence.Persistence _gthis = this;
			#line 204 "/my-component/src/persistence/Persistence.hx"
			if (( ((object) (getter.queryMapper) ) is global::haxe.lang.Function )) {
				#line 205 "/my-component/src/persistence/Persistence.hx"
				global::haxe.lang.Function queryMapper = ((global::haxe.lang.Function) (((object) (getter.queryMapper) )) );
				queryMapper.__hx_invoke2_o(default(double), queryValues, default(double), new global::persistence.Persistence_mapQuery_206__Fun(callback));
			}
			else if (global::Std.isOfType(((object) (getter.queryMapper) ), ((object) (typeof(string)) ))) {
				#line 211 "/my-component/src/persistence/Persistence.hx"
				string queryMapper1 = global::haxe.lang.Runtime.toString(((object) (getter.queryMapper) ));
				#line 213 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevResult ret = this.maglev.call(queryMapper1, ((global::maglev.MagLevArray) (this.convertToMagLev(((object) (new global::Array<object>(new object[]{queryValues})) ))) ));
				ret.onError(( (( global::persistence.Persistence_mapQuery_214__Fun.__hx_current != null )) ? (global::persistence.Persistence_mapQuery_214__Fun.__hx_current) : (global::persistence.Persistence_mapQuery_214__Fun.__hx_current = ((global::persistence.Persistence_mapQuery_214__Fun) (new global::persistence.Persistence_mapQuery_214__Fun()) )) ));
				#line 217 "/my-component/src/persistence/Persistence.hx"
				ret.onResult(new global::persistence.Persistence_mapQuery_217__Fun(callback, _gthis));
			}
			else {
				#line 223 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("queryMapper must be a string or function")) );
			}
			
		}
		#line default
		
		public virtual void query(global::persistence._Persistence.Getter getter, object queryValues, global::haxe.lang.Function callback) {
			#line 227 "/my-component/src/persistence/Persistence.hx"
			global::persistence.Persistence _gthis = this;
			#line 229 "/my-component/src/persistence/Persistence.hx"
			object raw_result = null;
			if (( ((object) (getter.strategyMethod) ) is global::haxe.lang.Function )) {
				#line 231 "/my-component/src/persistence/Persistence.hx"
				global::haxe.lang.Function strategyMethod = ((global::haxe.lang.Function) (((object) (getter.strategyMethod) )) );
				strategyMethod.__hx_invoke2_o(default(double), queryValues, default(double), new global::persistence.Persistence_query_232__Fun(callback));
			}
			else if (global::Std.isOfType(((object) (getter.strategyMethod) ), ((object) (typeof(string)) ))) {
				#line 237 "/my-component/src/persistence/Persistence.hx"
				string strategyMethod1 = global::haxe.lang.Runtime.toString(((object) (getter.strategyMethod) ));
				global::maglev.MagLevResult raw_maglev_result = null;
				#line 239 "/my-component/src/persistence/Persistence.hx"
				if (getter.useQueryValuesAsParams) {
					#line 240 "/my-component/src/persistence/Persistence.hx"
					raw_maglev_result = this.maglev.call(global::haxe.lang.Runtime.toString(((object) (getter.strategyMethod) )), ((global::maglev.MagLevArray) (this.convertToMagLev(queryValues)) ));
				}
				else {
					#line 242 "/my-component/src/persistence/Persistence.hx"
					raw_maglev_result = this.maglev.call(global::haxe.lang.Runtime.toString(((object) (getter.strategyMethod) )), ((global::maglev.MagLevArray) (this.convertToMagLev(((object) (new global::Array<object>(new object[]{queryValues})) ))) ));
				}
				
				#line 244 "/my-component/src/persistence/Persistence.hx"
				raw_maglev_result.onError(( (( global::persistence.Persistence_query_244__Fun.__hx_current != null )) ? (global::persistence.Persistence_query_244__Fun.__hx_current) : (global::persistence.Persistence_query_244__Fun.__hx_current = ((global::persistence.Persistence_query_244__Fun) (new global::persistence.Persistence_query_244__Fun()) )) ));
				#line 247 "/my-component/src/persistence/Persistence.hx"
				raw_maglev_result.onResult(new global::persistence.Persistence_query_247__Fun(callback, _gthis));
			}
			else {
				#line 253 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("strategyMethod must be a string or function")) );
			}
			
		}
		#line default
		
		public virtual void mapResults(global::persistence._Persistence.Getter getter, object queryResults, global::haxe.lang.Function callback) {
			#line 257 "/my-component/src/persistence/Persistence.hx"
			global::persistence.Persistence _gthis = this;
			#line 259 "/my-component/src/persistence/Persistence.hx"
			if (( ((object) (getter.resultMapper) ) is global::haxe.lang.Function )) {
				#line 260 "/my-component/src/persistence/Persistence.hx"
				global::haxe.lang.Function resultMapper = ((global::haxe.lang.Function) (((object) (getter.resultMapper) )) );
				resultMapper.__hx_invoke2_o(default(double), queryResults, default(double), new global::persistence.Persistence_mapResults_261__Fun(callback));
			}
			else if (global::Std.isOfType(((object) (getter.resultMapper) ), ((object) (typeof(string)) ))) {
				#line 266 "/my-component/src/persistence/Persistence.hx"
				string resultMapper1 = global::haxe.lang.Runtime.toString(((object) (getter.resultMapper) ));
				#line 268 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevResult maglev_result = this.maglev.call(resultMapper1, ((global::maglev.MagLevArray) (this.convertToMagLev(((object) (new global::Array<object>(new object[]{queryResults})) ))) ));
				maglev_result.onError(( (( global::persistence.Persistence_mapResults_269__Fun.__hx_current != null )) ? (global::persistence.Persistence_mapResults_269__Fun.__hx_current) : (global::persistence.Persistence_mapResults_269__Fun.__hx_current = ((global::persistence.Persistence_mapResults_269__Fun) (new global::persistence.Persistence_mapResults_269__Fun()) )) ));
				#line 272 "/my-component/src/persistence/Persistence.hx"
				maglev_result.onResult(new global::persistence.Persistence_mapResults_272__Fun(callback, _gthis));
			}
			else {
				#line 278 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("resultMapper must be a string or function")) );
			}
			
		}
		#line default
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 12 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 858513194:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						this.maglev = ((global::maglev.MagLev) (@value) );
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 883116808:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						this.getters = ((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (@value) ))) );
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 1678728017:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						this.mutators = ((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (@value) ))) );
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					default:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 12 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 199770554:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "mapResults", 199770554)) );
					}
					
					
					case 1575652104:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "query", 1575652104)) );
					}
					
					
					case 1429011148:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "mapQuery", 1429011148)) );
					}
					
					
					case 117802505:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "update", 117802505)) );
					}
					
					
					case 1776607685:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "mapUpdate", 1776607685)) );
					}
					
					
					case 263824376:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "convertToMagLev", 263824376)) );
					}
					
					
					case 907774356:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "convertToHaxe", 907774356)) );
					}
					
					
					case 1314583562:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "calcKey", 1314583562)) );
					}
					
					
					case 5144726:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get", 5144726)) );
					}
					
					
					case 1069478790:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "mutate", 1069478790)) );
					}
					
					
					case 1533285388:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "addGetter", 1533285388)) );
					}
					
					
					case 1860196033:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "addMutator", 1860196033)) );
					}
					
					
					case 858513194:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return this.maglev;
					}
					
					
					case 883116808:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return this.getters;
					}
					
					
					case 1678728017:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return this.mutators;
					}
					
					
					default:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 12 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 199770554:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						this.mapResults(((global::persistence._Persistence.Getter) (dynargs[0]) ), dynargs[1], ((global::haxe.lang.Function) (dynargs[2]) ));
						#line 12 "/my-component/src/persistence/Persistence.hx"
						break;
					}
					
					
					case 1575652104:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						this.query(((global::persistence._Persistence.Getter) (dynargs[0]) ), dynargs[1], ((global::haxe.lang.Function) (dynargs[2]) ));
						#line 12 "/my-component/src/persistence/Persistence.hx"
						break;
					}
					
					
					case 1429011148:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						this.mapQuery(((global::persistence._Persistence.Getter) (dynargs[0]) ), dynargs[1], ((global::haxe.lang.Function) (dynargs[2]) ));
						#line 12 "/my-component/src/persistence/Persistence.hx"
						break;
					}
					
					
					case 117802505:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						this.update(((global::persistence._Persistence.Mutator) (dynargs[0]) ), dynargs[1], ((global::haxe.lang.Function) (dynargs[2]) ));
						#line 12 "/my-component/src/persistence/Persistence.hx"
						break;
					}
					
					
					case 1776607685:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						this.mapUpdate(((global::persistence._Persistence.Mutator) (dynargs[0]) ), dynargs[1], ((global::haxe.lang.Function) (dynargs[2]) ));
						#line 12 "/my-component/src/persistence/Persistence.hx"
						break;
					}
					
					
					case 263824376:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return this.convertToMagLev(dynargs[0]);
					}
					
					
					case 907774356:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return this.convertToHaxe(((global::maglev.MagLevAny) (dynargs[0]) ));
					}
					
					
					case 1314583562:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return this.calcKey(global::haxe.lang.Runtime.toString(dynargs[0]), global::haxe.lang.Runtime.toString(dynargs[1]));
					}
					
					
					case 5144726:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						this.@get(global::haxe.lang.Runtime.toString(dynargs[0]), global::haxe.lang.Runtime.toString(dynargs[1]), dynargs[2], ((global::haxe.lang.Function) (dynargs[3]) ));
						#line 12 "/my-component/src/persistence/Persistence.hx"
						break;
					}
					
					
					case 1069478790:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						this.mutate(global::haxe.lang.Runtime.toString(dynargs[0]), global::haxe.lang.Runtime.toString(dynargs[1]), dynargs[2], ((global::haxe.lang.Function) (dynargs[3]) ));
						#line 12 "/my-component/src/persistence/Persistence.hx"
						break;
					}
					
					
					case 1533285388:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						this.addGetter(global::haxe.lang.Runtime.toString(dynargs[0]), global::haxe.lang.Runtime.toString(dynargs[1]), dynargs[2], ( (( dynargs.Length > 3 )) ? (dynargs[3]) : (null) ), ( (( dynargs.Length > 4 )) ? (dynargs[4]) : (null) ), global::haxe.lang.Null<object>.ofDynamic<bool>(( (( dynargs.Length > 5 )) ? (dynargs[5]) : (null) )));
						#line 12 "/my-component/src/persistence/Persistence.hx"
						break;
					}
					
					
					case 1860196033:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						this.addMutator(global::haxe.lang.Runtime.toString(dynargs[0]), global::haxe.lang.Runtime.toString(dynargs[1]), dynargs[2], ( (( dynargs.Length > 3 )) ? (dynargs[3]) : (null) ), global::haxe.lang.Null<object>.ofDynamic<bool>(( (( dynargs.Length > 4 )) ? (dynargs[4]) : (null) )));
						#line 12 "/my-component/src/persistence/Persistence.hx"
						break;
					}
					
					
					default:
					{
						#line 12 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				#line 12 "/my-component/src/persistence/Persistence.hx"
				return null;
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 12 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("maglev");
			#line 12 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("getters");
			#line 12 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("mutators");
			#line 12 "/my-component/src/persistence/Persistence.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_addMutator_80__Fun : global::haxe.lang.Function {
		
		public Persistence_addMutator_80__Fun() : base(2, 0) {
		}
		
		
		public static global::persistence.Persistence_addMutator_80__Fun __hx_current;
		
		public override object __hx_invoke2_o(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			#line 80 "/my-component/src/persistence/Persistence.hx"
			global::haxe.lang.Function cb = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::haxe.lang.Function) (((object) (__fn_float2) )) )) : (((global::haxe.lang.Function) (__fn_dyn2) )) );
			#line 80 "/my-component/src/persistence/Persistence.hx"
			object v = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			#line 80 "/my-component/src/persistence/Persistence.hx"
			cb.__hx_invoke1_o(default(double), v);
			#line 80 "/my-component/src/persistence/Persistence.hx"
			return null;
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_addGetter_91__Fun : global::haxe.lang.Function {
		
		public Persistence_addGetter_91__Fun() : base(2, 0) {
		}
		
		
		public static global::persistence.Persistence_addGetter_91__Fun __hx_current;
		
		public override object __hx_invoke2_o(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			#line 91 "/my-component/src/persistence/Persistence.hx"
			global::haxe.lang.Function cb = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::haxe.lang.Function) (((object) (__fn_float2) )) )) : (((global::haxe.lang.Function) (__fn_dyn2) )) );
			#line 91 "/my-component/src/persistence/Persistence.hx"
			object v = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			#line 91 "/my-component/src/persistence/Persistence.hx"
			cb.__hx_invoke1_o(default(double), v);
			#line 91 "/my-component/src/persistence/Persistence.hx"
			return null;
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_addGetter_94__Fun : global::haxe.lang.Function {
		
		public Persistence_addGetter_94__Fun() : base(2, 0) {
		}
		
		
		public static global::persistence.Persistence_addGetter_94__Fun __hx_current;
		
		public override object __hx_invoke2_o(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			#line 94 "/my-component/src/persistence/Persistence.hx"
			global::haxe.lang.Function cb = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::haxe.lang.Function) (((object) (__fn_float2) )) )) : (((global::haxe.lang.Function) (__fn_dyn2) )) );
			#line 94 "/my-component/src/persistence/Persistence.hx"
			object v = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			#line 94 "/my-component/src/persistence/Persistence.hx"
			cb.__hx_invoke1_o(default(double), v);
			#line 94 "/my-component/src/persistence/Persistence.hx"
			return null;
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_mutate_109__Fun : global::haxe.lang.Function {
		
		public Persistence_mutate_109__Fun(global::haxe.lang.Function callback) : base(1, 0) {
			#line 110 "/my-component/src/persistence/Persistence.hx"
			this.callback = callback;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 109 "/my-component/src/persistence/Persistence.hx"
			object updateResults = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			this.callback.__hx_invoke1_o(default(double), updateResults);
			return null;
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_mutate_108__Fun : global::haxe.lang.Function {
		
		public Persistence_mutate_108__Fun(global::persistence._Persistence.Mutator mutator, global::haxe.lang.Function callback, global::persistence.Persistence _gthis) : base(1, 0) {
			#line 109 "/my-component/src/persistence/Persistence.hx"
			this.mutator = mutator;
			#line 109 "/my-component/src/persistence/Persistence.hx"
			this.callback = callback;
			#line 109 "/my-component/src/persistence/Persistence.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 108 "/my-component/src/persistence/Persistence.hx"
			object mappedRecordData = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			this._gthis.update(this.mutator, mappedRecordData, new global::persistence.Persistence_mutate_109__Fun(this.callback));
			return null;
		}
		#line default
		
		public global::persistence._Persistence.Mutator mutator;
		
		public global::haxe.lang.Function callback;
		
		public global::persistence.Persistence _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_get_125__Fun : global::haxe.lang.Function {
		
		public Persistence_get_125__Fun(global::haxe.lang.Function callback) : base(1, 0) {
			#line 126 "/my-component/src/persistence/Persistence.hx"
			this.callback = callback;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 125 "/my-component/src/persistence/Persistence.hx"
			object mappedQueryValues = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			this.callback.__hx_invoke1_o(default(double), mappedQueryValues);
			return null;
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_get_124__Fun : global::haxe.lang.Function {
		
		public Persistence_get_124__Fun(global::persistence._Persistence.Getter getter, global::haxe.lang.Function callback, global::persistence.Persistence _gthis) : base(1, 0) {
			#line 125 "/my-component/src/persistence/Persistence.hx"
			this.getter = getter;
			#line 125 "/my-component/src/persistence/Persistence.hx"
			this.callback = callback;
			#line 125 "/my-component/src/persistence/Persistence.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 124 "/my-component/src/persistence/Persistence.hx"
			object queryResults = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			this._gthis.mapResults(this.getter, queryResults, new global::persistence.Persistence_get_125__Fun(this.callback));
			return null;
		}
		#line default
		
		public global::persistence._Persistence.Getter getter;
		
		public global::haxe.lang.Function callback;
		
		public global::persistence.Persistence _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_get_123__Fun : global::haxe.lang.Function {
		
		public Persistence_get_123__Fun(global::persistence._Persistence.Getter getter, global::haxe.lang.Function callback, global::persistence.Persistence _gthis) : base(1, 0) {
			#line 124 "/my-component/src/persistence/Persistence.hx"
			this.getter = getter;
			#line 124 "/my-component/src/persistence/Persistence.hx"
			this.callback = callback;
			#line 124 "/my-component/src/persistence/Persistence.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 123 "/my-component/src/persistence/Persistence.hx"
			object mappedQueryValues = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			this._gthis.query(this.getter, mappedQueryValues, new global::persistence.Persistence_get_124__Fun(this.getter, this.callback, this._gthis));
			return null;
		}
		#line default
		
		public global::persistence._Persistence.Getter getter;
		
		public global::haxe.lang.Function callback;
		
		public global::persistence.Persistence _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_mapUpdate_152__Fun : global::haxe.lang.Function {
		
		public Persistence_mapUpdate_152__Fun(global::haxe.lang.Function callback) : base(1, 0) {
			#line 153 "/my-component/src/persistence/Persistence.hx"
			this.callback = callback;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 152 "/my-component/src/persistence/Persistence.hx"
			object @params = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			this.callback.__hx_invoke1_o(default(double), @params);
			return null;
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_mapUpdate_160__Fun : global::haxe.lang.Function {
		
		public Persistence_mapUpdate_160__Fun() : base(1, 0) {
		}
		
		
		public static global::persistence.Persistence_mapUpdate_160__Fun __hx_current;
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 160 "/my-component/src/persistence/Persistence.hx"
			global::maglev.MagLevError error = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevError) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevError) (__fn_dyn1) )) );
			throw ((global::System.Exception) (global::haxe.Exception.thrown(error.getMessage())) );
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_mapUpdate_163__Fun : global::haxe.lang.Function {
		
		public Persistence_mapUpdate_163__Fun(global::haxe.lang.Function callback, global::persistence.Persistence _gthis) : base(1, 0) {
			#line 163 "/my-component/src/persistence/Persistence.hx"
			this.callback = callback;
			#line 163 "/my-component/src/persistence/Persistence.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 163 "/my-component/src/persistence/Persistence.hx"
			global::maglev.MagLevAny result = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevAny) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevAny) (__fn_dyn1) )) );
			this.callback.__hx_invoke1_o(default(double), this._gthis.convertToHaxe(result));
			#line 165 "/my-component/src/persistence/Persistence.hx"
			return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNull.create());
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
		public global::persistence.Persistence _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_update_177__Fun : global::haxe.lang.Function {
		
		public Persistence_update_177__Fun(global::haxe.lang.Function callback) : base(1, 0) {
			#line 178 "/my-component/src/persistence/Persistence.hx"
			this.callback = callback;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 177 "/my-component/src/persistence/Persistence.hx"
			object raw_result = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			this.callback.__hx_invoke1_o(default(double), raw_result);
			return null;
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_update_189__Fun : global::haxe.lang.Function {
		
		public Persistence_update_189__Fun() : base(1, 0) {
		}
		
		
		public static global::persistence.Persistence_update_189__Fun __hx_current;
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 189 "/my-component/src/persistence/Persistence.hx"
			global::maglev.MagLevError error = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevError) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevError) (__fn_dyn1) )) );
			throw ((global::System.Exception) (global::haxe.Exception.thrown(error.getMessage())) );
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_update_192__Fun : global::haxe.lang.Function {
		
		public Persistence_update_192__Fun(global::haxe.lang.Function callback, global::persistence.Persistence _gthis) : base(1, 0) {
			#line 192 "/my-component/src/persistence/Persistence.hx"
			this.callback = callback;
			#line 192 "/my-component/src/persistence/Persistence.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 192 "/my-component/src/persistence/Persistence.hx"
			global::maglev.MagLevAny result = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevAny) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevAny) (__fn_dyn1) )) );
			this.callback.__hx_invoke1_o(default(double), this._gthis.convertToHaxe(result));
			#line 194 "/my-component/src/persistence/Persistence.hx"
			return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNull.create());
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
		public global::persistence.Persistence _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_mapQuery_206__Fun : global::haxe.lang.Function {
		
		public Persistence_mapQuery_206__Fun(global::haxe.lang.Function callback) : base(1, 0) {
			#line 207 "/my-component/src/persistence/Persistence.hx"
			this.callback = callback;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 206 "/my-component/src/persistence/Persistence.hx"
			object mappedQueryValues = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			this.callback.__hx_invoke1_o(default(double), mappedQueryValues);
			return null;
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_mapQuery_214__Fun : global::haxe.lang.Function {
		
		public Persistence_mapQuery_214__Fun() : base(1, 0) {
		}
		
		
		public static global::persistence.Persistence_mapQuery_214__Fun __hx_current;
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 214 "/my-component/src/persistence/Persistence.hx"
			global::maglev.MagLevError error = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevError) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevError) (__fn_dyn1) )) );
			throw ((global::System.Exception) (global::haxe.Exception.thrown(error.getMessage())) );
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_mapQuery_217__Fun : global::haxe.lang.Function {
		
		public Persistence_mapQuery_217__Fun(global::haxe.lang.Function callback, global::persistence.Persistence _gthis) : base(1, 0) {
			#line 217 "/my-component/src/persistence/Persistence.hx"
			this.callback = callback;
			#line 217 "/my-component/src/persistence/Persistence.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 217 "/my-component/src/persistence/Persistence.hx"
			global::maglev.MagLevAny result = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevAny) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevAny) (__fn_dyn1) )) );
			this.callback.__hx_invoke1_o(default(double), this._gthis.convertToHaxe(result));
			#line 219 "/my-component/src/persistence/Persistence.hx"
			return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNull.create());
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
		public global::persistence.Persistence _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_query_232__Fun : global::haxe.lang.Function {
		
		public Persistence_query_232__Fun(global::haxe.lang.Function callback) : base(1, 0) {
			#line 233 "/my-component/src/persistence/Persistence.hx"
			this.callback = callback;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 232 "/my-component/src/persistence/Persistence.hx"
			object raw_result = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			this.callback.__hx_invoke1_o(default(double), raw_result);
			return null;
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_query_244__Fun : global::haxe.lang.Function {
		
		public Persistence_query_244__Fun() : base(1, 0) {
		}
		
		
		public static global::persistence.Persistence_query_244__Fun __hx_current;
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 244 "/my-component/src/persistence/Persistence.hx"
			global::maglev.MagLevError error = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevError) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevError) (__fn_dyn1) )) );
			throw ((global::System.Exception) (global::haxe.Exception.thrown(error.getMessage())) );
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_query_247__Fun : global::haxe.lang.Function {
		
		public Persistence_query_247__Fun(global::haxe.lang.Function callback, global::persistence.Persistence _gthis) : base(1, 0) {
			#line 247 "/my-component/src/persistence/Persistence.hx"
			this.callback = callback;
			#line 247 "/my-component/src/persistence/Persistence.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 247 "/my-component/src/persistence/Persistence.hx"
			global::maglev.MagLevAny result = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevAny) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevAny) (__fn_dyn1) )) );
			this.callback.__hx_invoke1_o(default(double), this._gthis.convertToHaxe(result));
			#line 249 "/my-component/src/persistence/Persistence.hx"
			return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNull.create());
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
		public global::persistence.Persistence _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_mapResults_261__Fun : global::haxe.lang.Function {
		
		public Persistence_mapResults_261__Fun(global::haxe.lang.Function callback) : base(1, 0) {
			#line 262 "/my-component/src/persistence/Persistence.hx"
			this.callback = callback;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 261 "/my-component/src/persistence/Persistence.hx"
			object mappedResults = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			this.callback.__hx_invoke1_o(default(double), mappedResults);
			return null;
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_mapResults_269__Fun : global::haxe.lang.Function {
		
		public Persistence_mapResults_269__Fun() : base(1, 0) {
		}
		
		
		public static global::persistence.Persistence_mapResults_269__Fun __hx_current;
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 269 "/my-component/src/persistence/Persistence.hx"
			global::maglev.MagLevError error = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevError) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevError) (__fn_dyn1) )) );
			throw ((global::System.Exception) (global::haxe.Exception.thrown(error.getMessage())) );
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_mapResults_272__Fun : global::haxe.lang.Function {
		
		public Persistence_mapResults_272__Fun(global::haxe.lang.Function callback, global::persistence.Persistence _gthis) : base(1, 0) {
			#line 272 "/my-component/src/persistence/Persistence.hx"
			this.callback = callback;
			#line 272 "/my-component/src/persistence/Persistence.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 272 "/my-component/src/persistence/Persistence.hx"
			global::maglev.MagLevAny result = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevAny) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevAny) (__fn_dyn1) )) );
			this.callback.__hx_invoke1_o(default(double), this._gthis.convertToHaxe(result));
			#line 274 "/my-component/src/persistence/Persistence.hx"
			return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNull.create());
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
		public global::persistence.Persistence _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence___hx_ctor_persistence_Persistence_22__Fun : global::haxe.lang.Function {
		
		public Persistence___hx_ctor_persistence_Persistence_22__Fun(global::persistence.Persistence _gthis) : base(1, 0) {
			#line 22 "/my-component/src/persistence/Persistence.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 22 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				string recordType = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
				#line 24 "/my-component/src/persistence/Persistence.hx"
				string operationName = (((global::maglev.MagLevString) (args.@get(1)) )).getString();
				object strategyMethod = this._gthis.convertToHaxe(args.@get(2));
				#line 26 "/my-component/src/persistence/Persistence.hx"
				object updateMapper = null;
				if (( args.size() > 3 )) {
					#line 28 "/my-component/src/persistence/Persistence.hx"
					updateMapper = this._gthis.convertToHaxe(args.@get(3));
				}
				
				#line 30 "/my-component/src/persistence/Persistence.hx"
				global::haxe.lang.Null<bool> useRecordDataAsParams = default(global::haxe.lang.Null<bool>);
				if (( args.size() > 4 )) {
					#line 32 "/my-component/src/persistence/Persistence.hx"
					useRecordDataAsParams = global::haxe.lang.Null<object>.ofDynamic<bool>(((object) (this._gthis.convertToHaxe(args.@get(4))) ));
				}
				
				#line 34 "/my-component/src/persistence/Persistence.hx"
				this._gthis.addMutator(recordType, operationName, strategyMethod, updateMapper, useRecordDataAsParams);
				return global::maglev.MagLevResult.fromResult(global::maglev.MagLevBoolean.fromBool(true));
			}
			#line default
		}
		
		
		public global::persistence.Persistence _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence___hx_ctor_persistence_Persistence_37__Fun : global::haxe.lang.Function {
		
		public Persistence___hx_ctor_persistence_Persistence_37__Fun(global::persistence.Persistence _gthis) : base(1, 0) {
			#line 37 "/my-component/src/persistence/Persistence.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 37 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				string recordType = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
				#line 39 "/my-component/src/persistence/Persistence.hx"
				string operationName = (((global::maglev.MagLevString) (args.@get(1)) )).getString();
				object strategyMethod = this._gthis.convertToHaxe(args.@get(2));
				#line 41 "/my-component/src/persistence/Persistence.hx"
				object queryMapper = null;
				if (( args.size() >= 4 )) {
					#line 43 "/my-component/src/persistence/Persistence.hx"
					queryMapper = this._gthis.convertToHaxe(args.@get(3));
				}
				
				#line 45 "/my-component/src/persistence/Persistence.hx"
				object resultMapper = null;
				if (( args.size() >= 5 )) {
					#line 47 "/my-component/src/persistence/Persistence.hx"
					resultMapper = this._gthis.convertToHaxe(args.@get(4));
				}
				
				#line 49 "/my-component/src/persistence/Persistence.hx"
				global::haxe.lang.Null<bool> useQueryValuesAsParams = default(global::haxe.lang.Null<bool>);
				if (( args.size() >= 6 )) {
					#line 51 "/my-component/src/persistence/Persistence.hx"
					useQueryValuesAsParams = new global::haxe.lang.Null<bool>((((global::maglev.MagLevBoolean) (args.@get(5)) )).getBool(), true);
				}
				
				#line 53 "/my-component/src/persistence/Persistence.hx"
				this._gthis.addGetter(recordType, operationName, strategyMethod, queryMapper, resultMapper, useQueryValuesAsParams);
				return global::maglev.MagLevResult.fromResult(global::maglev.MagLevBoolean.fromBool(true));
			}
			#line default
		}
		
		
		public global::persistence.Persistence _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence___hx_ctor_persistence_Persistence_61__Fun : global::haxe.lang.Function {
		
		public Persistence___hx_ctor_persistence_Persistence_61__Fun(global::maglev.MagLevResult maglevResult, global::persistence.Persistence _gthis) : base(1, 0) {
			#line 62 "/my-component/src/persistence/Persistence.hx"
			this.maglevResult = maglevResult;
			#line 62 "/my-component/src/persistence/Persistence.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 61 "/my-component/src/persistence/Persistence.hx"
			object haxeResult = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			this.maglevResult.setResult(this._gthis.convertToMagLev(haxeResult));
			return null;
		}
		#line default
		
		public global::maglev.MagLevResult maglevResult;
		
		public global::persistence.Persistence _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence___hx_ctor_persistence_Persistence_56__Fun : global::haxe.lang.Function {
		
		public Persistence___hx_ctor_persistence_Persistence_56__Fun(global::persistence.Persistence _gthis) : base(1, 0) {
			#line 56 "/my-component/src/persistence/Persistence.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 56 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				string recordType = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
				#line 58 "/my-component/src/persistence/Persistence.hx"
				string operationName = (((global::maglev.MagLevString) (args.@get(1)) )).getString();
				object recordData = this._gthis.convertToHaxe(((global::maglev.MagLevArray) (args.@get(2)) ));
				#line 60 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevResult maglevResult = global::maglev.MagLevResult.createAsync();
				this._gthis.mutate(recordType, operationName, recordData, new global::persistence.Persistence___hx_ctor_persistence_Persistence_61__Fun(maglevResult, this._gthis));
				#line 64 "/my-component/src/persistence/Persistence.hx"
				return maglevResult;
			}
			#line default
		}
		
		
		public global::persistence.Persistence _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence___hx_ctor_persistence_Persistence_71__Fun : global::haxe.lang.Function {
		
		public Persistence___hx_ctor_persistence_Persistence_71__Fun(global::maglev.MagLevResult maglevResult, global::persistence.Persistence _gthis) : base(1, 0) {
			#line 72 "/my-component/src/persistence/Persistence.hx"
			this.maglevResult = maglevResult;
			#line 72 "/my-component/src/persistence/Persistence.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 71 "/my-component/src/persistence/Persistence.hx"
			object haxeResult = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			this.maglevResult.setResult(this._gthis.convertToMagLev(haxeResult));
			return null;
		}
		#line default
		
		public global::maglev.MagLevResult maglevResult;
		
		public global::persistence.Persistence _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence___hx_ctor_persistence_Persistence_66__Fun : global::haxe.lang.Function {
		
		public Persistence___hx_ctor_persistence_Persistence_66__Fun(global::persistence.Persistence _gthis) : base(1, 0) {
			#line 66 "/my-component/src/persistence/Persistence.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 66 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				string recordType = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
				#line 68 "/my-component/src/persistence/Persistence.hx"
				string operationName = (((global::maglev.MagLevString) (args.@get(1)) )).getString();
				object queryValues = this._gthis.convertToHaxe(((global::maglev.MagLevArray) (args.@get(2)) ));
				#line 70 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevResult maglevResult = global::maglev.MagLevResult.createAsync();
				this._gthis.@get(recordType, operationName, queryValues, new global::persistence.Persistence___hx_ctor_persistence_Persistence_71__Fun(maglevResult, this._gthis));
				#line 74 "/my-component/src/persistence/Persistence.hx"
				return maglevResult;
			}
			#line default
		}
		
		
		public global::persistence.Persistence _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence._Persistence {
	public class Mutator : global::haxe.lang.HxObject {
		
		static Mutator() {
			unchecked{
				#line 287 "/my-component/src/persistence/Persistence.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{5541879, 13816588}, new string[]{"obj", "SuppressWarnings"});
				#line 287 "/my-component/src/persistence/Persistence.hx"
				{
					#line 287 "/my-component/src/persistence/Persistence.hx"
					{
						#line 287 "/my-component/src/persistence/Persistence.hx"
						object __temp_odecl1 = new global::haxe.lang.DynamicObject(new int[]{13816588}, new object[]{new global::Array<object>(new object[]{"checkstyle:FieldDocComment"})}, new int[]{}, new double[]{});
						#line 287 "/my-component/src/persistence/Persistence.hx"
						global::persistence._Persistence.Mutator.__meta__ = new global::haxe.lang.DynamicObject(new int[]{5541879}, new object[]{__temp_odecl1}, new int[]{}, new double[]{});
					}
					
				}
				
			}
		}
		#line default
		
		public Mutator(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Mutator(string recordType, object strategyMethod, object updateMapper, bool useRecordDataAsParams) {
			#line 293 "/my-component/src/persistence/Persistence.hx"
			global::persistence._Persistence.Mutator.__hx_ctor_persistence__Persistence_Mutator(this, recordType, strategyMethod, updateMapper, useRecordDataAsParams);
		}
		#line default
		
		protected static void __hx_ctor_persistence__Persistence_Mutator(global::persistence._Persistence.Mutator __hx_this, string recordType, object strategyMethod, object updateMapper, bool useRecordDataAsParams) {
			#line 294 "/my-component/src/persistence/Persistence.hx"
			if ((  ! (global::Std.isOfType(((object) (strategyMethod) ), ((object) (typeof(string)) )))  &&  ! (( ((object) (strategyMethod) ) is global::haxe.lang.Function ))  )) {
				#line 295 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("strategyMethod must be a string or function")) );
			}
			
			#line 297 "/my-component/src/persistence/Persistence.hx"
			if ((  ! (global::Std.isOfType(((object) (updateMapper) ), ((object) (typeof(string)) )))  &&  ! (( ((object) (updateMapper) ) is global::haxe.lang.Function ))  )) {
				#line 298 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("updateMapper must be a string or function")) );
			}
			
			#line 300 "/my-component/src/persistence/Persistence.hx"
			__hx_this.recordType = recordType;
			__hx_this.strategyMethod = strategyMethod;
			#line 302 "/my-component/src/persistence/Persistence.hx"
			__hx_this.updateMapper = updateMapper;
			__hx_this.useRecordDataAsParams = useRecordDataAsParams;
		}
		#line default
		
		public static object __meta__;
		
		public string recordType;
		
		public object strategyMethod;
		
		public object updateMapper;
		
		public bool useRecordDataAsParams;
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 287 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 954563242:
					{
						#line 287 "/my-component/src/persistence/Persistence.hx"
						this.updateMapper = ((object) (@value) );
						#line 287 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 1853356980:
					{
						#line 287 "/my-component/src/persistence/Persistence.hx"
						this.strategyMethod = ((object) (@value) );
						#line 287 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					default:
					{
						#line 287 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 287 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 6101114:
					{
						#line 287 "/my-component/src/persistence/Persistence.hx"
						this.useRecordDataAsParams = global::haxe.lang.Runtime.toBool(@value);
						#line 287 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 954563242:
					{
						#line 287 "/my-component/src/persistence/Persistence.hx"
						this.updateMapper = ((object) (@value) );
						#line 287 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 1853356980:
					{
						#line 287 "/my-component/src/persistence/Persistence.hx"
						this.strategyMethod = ((object) (@value) );
						#line 287 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 1633399275:
					{
						#line 287 "/my-component/src/persistence/Persistence.hx"
						this.recordType = global::haxe.lang.Runtime.toString(@value);
						#line 287 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					default:
					{
						#line 287 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 287 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 6101114:
					{
						#line 287 "/my-component/src/persistence/Persistence.hx"
						return this.useRecordDataAsParams;
					}
					
					
					case 954563242:
					{
						#line 287 "/my-component/src/persistence/Persistence.hx"
						return this.updateMapper;
					}
					
					
					case 1853356980:
					{
						#line 287 "/my-component/src/persistence/Persistence.hx"
						return this.strategyMethod;
					}
					
					
					case 1633399275:
					{
						#line 287 "/my-component/src/persistence/Persistence.hx"
						return this.recordType;
					}
					
					
					default:
					{
						#line 287 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 287 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 954563242:
					{
						#line 287 "/my-component/src/persistence/Persistence.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(this.updateMapper)) );
					}
					
					
					case 1853356980:
					{
						#line 287 "/my-component/src/persistence/Persistence.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(this.strategyMethod)) );
					}
					
					
					default:
					{
						#line 287 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 287 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("useRecordDataAsParams");
			#line 287 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("updateMapper");
			#line 287 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("strategyMethod");
			#line 287 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("recordType");
			#line 287 "/my-component/src/persistence/Persistence.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence._Persistence {
	public class Getter : global::haxe.lang.HxObject {
		
		static Getter() {
			unchecked{
				#line 311 "/my-component/src/persistence/Persistence.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{5541879, 13816588}, new string[]{"obj", "SuppressWarnings"});
				#line 311 "/my-component/src/persistence/Persistence.hx"
				{
					#line 311 "/my-component/src/persistence/Persistence.hx"
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						object __temp_odecl1 = new global::haxe.lang.DynamicObject(new int[]{13816588}, new object[]{new global::Array<object>(new object[]{"checkstyle:FieldDocComment"})}, new int[]{}, new double[]{});
						#line 311 "/my-component/src/persistence/Persistence.hx"
						global::persistence._Persistence.Getter.__meta__ = new global::haxe.lang.DynamicObject(new int[]{5541879}, new object[]{__temp_odecl1}, new int[]{}, new double[]{});
					}
					
				}
				
			}
		}
		#line default
		
		public Getter(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Getter(string recordType, object strategyMethod, object queryMapper, object resultMapper, bool useQueryValuesAsParams) {
			#line 318 "/my-component/src/persistence/Persistence.hx"
			global::persistence._Persistence.Getter.__hx_ctor_persistence__Persistence_Getter(this, recordType, strategyMethod, queryMapper, resultMapper, useQueryValuesAsParams);
		}
		#line default
		
		protected static void __hx_ctor_persistence__Persistence_Getter(global::persistence._Persistence.Getter __hx_this, string recordType, object strategyMethod, object queryMapper, object resultMapper, bool useQueryValuesAsParams) {
			#line 319 "/my-component/src/persistence/Persistence.hx"
			if ((  ! (global::Std.isOfType(((object) (strategyMethod) ), ((object) (typeof(string)) )))  &&  ! (( ((object) (strategyMethod) ) is global::haxe.lang.Function ))  )) {
				#line 320 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("strategyMethod must be a string or function")) );
			}
			
			#line 322 "/my-component/src/persistence/Persistence.hx"
			if ((  ! (global::Std.isOfType(((object) (queryMapper) ), ((object) (typeof(string)) )))  &&  ! (( ((object) (queryMapper) ) is global::haxe.lang.Function ))  )) {
				#line 323 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("queryMapper must be a string or function")) );
			}
			
			#line 325 "/my-component/src/persistence/Persistence.hx"
			if ((  ! (global::Std.isOfType(((object) (resultMapper) ), ((object) (typeof(string)) )))  &&  ! (( ((object) (resultMapper) ) is global::haxe.lang.Function ))  )) {
				#line 326 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("resultMapper must be a string or function")) );
			}
			
			#line 328 "/my-component/src/persistence/Persistence.hx"
			__hx_this.recordType = recordType;
			__hx_this.strategyMethod = strategyMethod;
			#line 330 "/my-component/src/persistence/Persistence.hx"
			__hx_this.queryMapper = queryMapper;
			__hx_this.resultMapper = resultMapper;
			#line 332 "/my-component/src/persistence/Persistence.hx"
			__hx_this.useQueryValuesAsParams = useQueryValuesAsParams;
		}
		#line default
		
		public static object __meta__;
		
		public string recordType;
		
		public object strategyMethod;
		
		public object queryMapper;
		
		public object resultMapper;
		
		public bool useQueryValuesAsParams;
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 311 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 1333802110:
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						this.resultMapper = ((object) (@value) );
						#line 311 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 189188329:
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						this.queryMapper = ((object) (@value) );
						#line 311 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 1853356980:
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						this.strategyMethod = ((object) (@value) );
						#line 311 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					default:
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 311 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 591874299:
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						this.useQueryValuesAsParams = global::haxe.lang.Runtime.toBool(@value);
						#line 311 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 1333802110:
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						this.resultMapper = ((object) (@value) );
						#line 311 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 189188329:
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						this.queryMapper = ((object) (@value) );
						#line 311 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 1853356980:
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						this.strategyMethod = ((object) (@value) );
						#line 311 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 1633399275:
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						this.recordType = global::haxe.lang.Runtime.toString(@value);
						#line 311 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					default:
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 311 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 591874299:
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						return this.useQueryValuesAsParams;
					}
					
					
					case 1333802110:
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						return this.resultMapper;
					}
					
					
					case 189188329:
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						return this.queryMapper;
					}
					
					
					case 1853356980:
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						return this.strategyMethod;
					}
					
					
					case 1633399275:
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						return this.recordType;
					}
					
					
					default:
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 311 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 1333802110:
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(this.resultMapper)) );
					}
					
					
					case 189188329:
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(this.queryMapper)) );
					}
					
					
					case 1853356980:
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(this.strategyMethod)) );
					}
					
					
					default:
					{
						#line 311 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 311 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("useQueryValuesAsParams");
			#line 311 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("resultMapper");
			#line 311 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("queryMapper");
			#line 311 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("strategyMethod");
			#line 311 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("recordType");
			#line 311 "/my-component/src/persistence/Persistence.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}


