// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence : global::haxe.lang.HxObject {
		
		static Persistence() {
			unchecked{
				#line 10 "/my-component/src/persistence/Persistence.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{5144726, 5541879, 13816588, 263824376, 407283053, 907774356, 1069478790, 1224901875, 1314583562, 1533285388, 1860196033}, new string[]{"get", "obj", "SuppressWarnings", "convertToMagLev", "hasNext", "convertToHaxe", "mutate", "next", "calcKey", "addGetter", "addMutator"});
				#line 10 "/my-component/src/persistence/Persistence.hx"
				{
					#line 10 "/my-component/src/persistence/Persistence.hx"
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						object __temp_odecl1 = new global::haxe.lang.DynamicObject(new int[]{13816588}, new object[]{new global::Array<object>(new object[]{new global::Array<object>(new object[]{"checkstyle:FieldDocComment", "checkstyle:LocalVariableName", "checkstyle:MultipleStringLiterals", "checkstyle:MagicNumber"})})}, new int[]{}, new double[]{});
						#line 10 "/my-component/src/persistence/Persistence.hx"
						global::persistence.Persistence.__meta__ = new global::haxe.lang.DynamicObject(new int[]{5541879}, new object[]{__temp_odecl1}, new int[]{}, new double[]{});
					}
					
				}
				
			}
		}
		#line default
		
		public Persistence(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Persistence(global::maglev.MagLev bus) {
			#line 16 "/my-component/src/persistence/Persistence.hx"
			global::persistence.Persistence.__hx_ctor_persistence_Persistence(this, bus);
		}
		#line default
		
		protected static void __hx_ctor_persistence_Persistence(global::persistence.Persistence __hx_this, global::maglev.MagLev bus) {
			#line 16 "/my-component/src/persistence/Persistence.hx"
			global::persistence.Persistence _gthis = __hx_this;
			__hx_this.mutators = new global::haxe.ds.StringMap<object>();
			#line 18 "/my-component/src/persistence/Persistence.hx"
			__hx_this.getters = new global::haxe.ds.StringMap<object>();
			__hx_this.maglev = bus;
			#line 20 "/my-component/src/persistence/Persistence.hx"
			__hx_this.maglev.register("Persistence.AddMutator", global::maglev.MagLevFunction.fromFunction(new global::persistence.Persistence___hx_ctor_persistence_Persistence_20__Fun(_gthis)));
			#line 35 "/my-component/src/persistence/Persistence.hx"
			__hx_this.maglev.register("Persistence.AddGetter", global::maglev.MagLevFunction.fromFunction(new global::persistence.Persistence___hx_ctor_persistence_Persistence_35__Fun(_gthis)));
			#line 54 "/my-component/src/persistence/Persistence.hx"
			__hx_this.maglev.register("Persistence.Mutate", global::maglev.MagLevFunction.fromFunction(new global::persistence.Persistence___hx_ctor_persistence_Persistence_54__Fun(_gthis)));
			#line 61 "/my-component/src/persistence/Persistence.hx"
			__hx_this.maglev.register("Persistence.Get", global::maglev.MagLevFunction.fromFunction(new global::persistence.Persistence___hx_ctor_persistence_Persistence_61__Fun(_gthis)));
		}
		#line default
		
		public static object __meta__;
		
		public global::haxe.ds.StringMap<object> mutators;
		
		public global::haxe.ds.StringMap<object> getters;
		
		public global::maglev.MagLev maglev;
		
		public virtual void addMutator(string recordType, string operationName, object strategyMethod, object updateMapper, global::haxe.lang.Null<bool> useRecordDataAsParams) {
			#line 71 "/my-component/src/persistence/Persistence.hx"
			if (( updateMapper == null )) {
				#line 72 "/my-component/src/persistence/Persistence.hx"
				updateMapper = ((object) (( (( global::persistence.Persistence_addMutator_72__Fun.__hx_current != null )) ? (global::persistence.Persistence_addMutator_72__Fun.__hx_current) : (global::persistence.Persistence_addMutator_72__Fun.__hx_current = ((global::persistence.Persistence_addMutator_72__Fun) (new global::persistence.Persistence_addMutator_72__Fun()) )) )) );
			}
			
			#line 74 "/my-component/src/persistence/Persistence.hx"
			if ( ! (useRecordDataAsParams.hasValue) ) {
				#line 75 "/my-component/src/persistence/Persistence.hx"
				useRecordDataAsParams = new global::haxe.lang.Null<bool>(false, true);
			}
			
			#line 77 "/my-component/src/persistence/Persistence.hx"
			global::persistence._Persistence.Mutator mutator = new global::persistence._Persistence.Mutator(recordType, strategyMethod, updateMapper, (useRecordDataAsParams).@value);
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.mutators) )) ))) ).@set(this.calcKey(recordType, operationName), mutator);
		}
		#line default
		
		public virtual void addGetter(string recordType, string operationName, object strategyMethod, object queryMapper, object resultMapper, global::haxe.lang.Null<bool> useQueryValuesAsParams) {
			#line 82 "/my-component/src/persistence/Persistence.hx"
			if (( queryMapper == null )) {
				#line 83 "/my-component/src/persistence/Persistence.hx"
				queryMapper = ((object) (( (( global::persistence.Persistence_addGetter_83__Fun.__hx_current != null )) ? (global::persistence.Persistence_addGetter_83__Fun.__hx_current) : (global::persistence.Persistence_addGetter_83__Fun.__hx_current = ((global::persistence.Persistence_addGetter_83__Fun) (new global::persistence.Persistence_addGetter_83__Fun()) )) )) );
			}
			
			#line 85 "/my-component/src/persistence/Persistence.hx"
			if (( resultMapper == null )) {
				#line 86 "/my-component/src/persistence/Persistence.hx"
				resultMapper = ((object) (( (( global::persistence.Persistence_addGetter_86__Fun.__hx_current != null )) ? (global::persistence.Persistence_addGetter_86__Fun.__hx_current) : (global::persistence.Persistence_addGetter_86__Fun.__hx_current = ((global::persistence.Persistence_addGetter_86__Fun) (new global::persistence.Persistence_addGetter_86__Fun()) )) )) );
			}
			
			#line 88 "/my-component/src/persistence/Persistence.hx"
			if ( ! (useQueryValuesAsParams.hasValue) ) {
				#line 89 "/my-component/src/persistence/Persistence.hx"
				useQueryValuesAsParams = new global::haxe.lang.Null<bool>(false, true);
			}
			
			#line 91 "/my-component/src/persistence/Persistence.hx"
			global::persistence._Persistence.Getter getter = new global::persistence._Persistence.Getter(recordType, strategyMethod, queryMapper, resultMapper, (useQueryValuesAsParams).@value);
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.getters) )) ))) ).@set(this.calcKey(recordType, operationName), getter);
		}
		#line default
		
		public virtual void mutate(string recordType, string operationName, object recordData) {
			#line 96 "/my-component/src/persistence/Persistence.hx"
			if (((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.mutators) )) ))) ).exists(this.calcKey(recordType, operationName))) {
				#line 97 "/my-component/src/persistence/Persistence.hx"
				global::persistence._Persistence.Mutator mutator = ((global::persistence._Persistence.Mutator) ((((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.mutators) )) ))) ).@get(this.calcKey(recordType, operationName))).@value) );
				#line 99 "/my-component/src/persistence/Persistence.hx"
				object @params = null;
				if (( ((object) (mutator.updateMapper) ) is global::haxe.lang.Function )) {
					#line 101 "/my-component/src/persistence/Persistence.hx"
					global::haxe.lang.Function updateMapper = ((global::haxe.lang.Function) (((object) (mutator.updateMapper) )) );
					@params = ((object) (updateMapper.__hx_invoke1_o(default(double), recordData)) );
				}
				else if (global::Std.isOfType(((object) (mutator.updateMapper) ), ((object) (typeof(string)) ))) {
					#line 105 "/my-component/src/persistence/Persistence.hx"
					string updateMapper1 = global::haxe.lang.Runtime.toString(((object) (mutator.updateMapper) ));
					#line 107 "/my-component/src/persistence/Persistence.hx"
					@params = ((object) (this.maglev.call(updateMapper1, ((global::maglev.MagLevArray) (this.convertToMagLev(((object) (new global::Array<object>(new object[]{recordData})) ))) ))) );
				}
				else {
					#line 110 "/my-component/src/persistence/Persistence.hx"
					throw ((global::System.Exception) (global::haxe.Exception.thrown("updateMapper must be a string or function")) );
				}
				
				#line 113 "/my-component/src/persistence/Persistence.hx"
				object raw_result = null;
				if (( ((object) (mutator.strategyMethod) ) is global::haxe.lang.Function )) {
					#line 115 "/my-component/src/persistence/Persistence.hx"
					global::haxe.lang.Function strategyMethod = ((global::haxe.lang.Function) (((object) (mutator.strategyMethod) )) );
					raw_result = ((object) (strategyMethod.__hx_invoke1_o(default(double), @params)) );
				}
				else if (global::Std.isOfType(((object) (mutator.strategyMethod) ), ((object) (typeof(string)) ))) {
					#line 119 "/my-component/src/persistence/Persistence.hx"
					string strategyMethod1 = global::haxe.lang.Runtime.toString(((object) (mutator.strategyMethod) ));
					if (mutator.useRecordDataAsParams) {
						#line 121 "/my-component/src/persistence/Persistence.hx"
						raw_result = ((object) (this.maglev.call(strategyMethod1, ((global::maglev.MagLevArray) (this.convertToMagLev(@params)) ))) );
					}
					else {
						#line 123 "/my-component/src/persistence/Persistence.hx"
						raw_result = ((object) (this.maglev.call(strategyMethod1, ((global::maglev.MagLevArray) (this.convertToMagLev(((object) (new global::Array<object>(new object[]{@params})) ))) ))) );
					}
					
				}
				else {
					#line 127 "/my-component/src/persistence/Persistence.hx"
					throw ((global::System.Exception) (global::haxe.Exception.thrown("strategyMethod must be a string or function")) );
				}
				
			}
			else {
				#line 131 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("the specified mutator has not been added")) );
			}
			
		}
		#line default
		
		public virtual object @get(string recordType, string operationName, object queryValues) {
			#line 136 "/my-component/src/persistence/Persistence.hx"
			if (((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.getters) )) ))) ).exists(this.calcKey(recordType, operationName))) {
				#line 137 "/my-component/src/persistence/Persistence.hx"
				global::persistence._Persistence.Getter getter = ((global::persistence._Persistence.Getter) ((((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.getters) )) ))) ).@get(this.calcKey(recordType, operationName))).@value) );
				#line 139 "/my-component/src/persistence/Persistence.hx"
				object query = null;
				if (( ((object) (getter.queryMapper) ) is global::haxe.lang.Function )) {
					#line 141 "/my-component/src/persistence/Persistence.hx"
					global::haxe.lang.Function queryMapper = ((global::haxe.lang.Function) (((object) (getter.queryMapper) )) );
					query = ((object) (queryMapper.__hx_invoke1_o(default(double), queryValues)) );
				}
				else if (global::Std.isOfType(((object) (getter.queryMapper) ), ((object) (typeof(string)) ))) {
					#line 145 "/my-component/src/persistence/Persistence.hx"
					string queryMapper1 = global::haxe.lang.Runtime.toString(((object) (getter.queryMapper) ));
					#line 147 "/my-component/src/persistence/Persistence.hx"
					query = ((object) (this.maglev.call(queryMapper1, ((global::maglev.MagLevArray) (this.convertToMagLev(((object) (new global::Array<object>(new object[]{queryValues})) ))) ))) );
				}
				else {
					#line 150 "/my-component/src/persistence/Persistence.hx"
					throw ((global::System.Exception) (global::haxe.Exception.thrown("queryMapper must be a string or function")) );
				}
				
				#line 153 "/my-component/src/persistence/Persistence.hx"
				object raw_result = null;
				if (( ((object) (getter.strategyMethod) ) is global::haxe.lang.Function )) {
					#line 155 "/my-component/src/persistence/Persistence.hx"
					global::haxe.lang.Function strategyMethod = ((global::haxe.lang.Function) (((object) (getter.strategyMethod) )) );
					raw_result = ((object) (strategyMethod.__hx_invoke1_o(default(double), query)) );
				}
				else if (global::Std.isOfType(((object) (getter.strategyMethod) ), ((object) (typeof(string)) ))) {
					#line 159 "/my-component/src/persistence/Persistence.hx"
					string strategyMethod1 = global::haxe.lang.Runtime.toString(((object) (getter.strategyMethod) ));
					if (getter.useQueryValuesAsParams) {
						#line 161 "/my-component/src/persistence/Persistence.hx"
						global::maglev.MagLevResult raw_result_result = this.maglev.call(global::haxe.lang.Runtime.toString(((object) (getter.strategyMethod) )), ((global::maglev.MagLevArray) (this.convertToMagLev(query)) ));
						raw_result = this.convertToHaxe(raw_result_result.getResult());
					}
					else {
						#line 164 "/my-component/src/persistence/Persistence.hx"
						raw_result = ((object) (this.maglev.call(global::haxe.lang.Runtime.toString(((object) (getter.strategyMethod) )), ((global::maglev.MagLevArray) (this.convertToMagLev(((object) (new global::Array<object>(new object[]{query})) ))) ))) );
						#line 164 "/my-component/src/persistence/Persistence.hx"
						global::maglev.MagLevResult raw_result_result1 = ((global::maglev.MagLevResult) (((object) (raw_result) )) );
						raw_result = this.convertToHaxe(raw_result_result1.getResult());
					}
					
				}
				else {
					#line 169 "/my-component/src/persistence/Persistence.hx"
					throw ((global::System.Exception) (global::haxe.Exception.thrown("strategyMethod must be a string or function")) );
				}
				
				#line 172 "/my-component/src/persistence/Persistence.hx"
				object result = null;
				if (( ((object) (getter.resultMapper) ) is global::haxe.lang.Function )) {
					#line 174 "/my-component/src/persistence/Persistence.hx"
					global::haxe.lang.Function resultMapper = ((global::haxe.lang.Function) (((object) (getter.resultMapper) )) );
					result = ((object) (resultMapper.__hx_invoke1_o(default(double), raw_result)) );
				}
				else if (global::Std.isOfType(((object) (getter.resultMapper) ), ((object) (typeof(string)) ))) {
					#line 178 "/my-component/src/persistence/Persistence.hx"
					string resultMapper1 = global::haxe.lang.Runtime.toString(((object) (getter.resultMapper) ));
					#line 180 "/my-component/src/persistence/Persistence.hx"
					result = ((object) (this.maglev.call(resultMapper1, ((global::maglev.MagLevArray) (this.convertToMagLev(((object) (new global::Array<object>(new object[]{raw_result})) ))) ))) );
				}
				else {
					#line 183 "/my-component/src/persistence/Persistence.hx"
					throw ((global::System.Exception) (global::haxe.Exception.thrown("resultMapper must be a string or function")) );
				}
				
				#line 185 "/my-component/src/persistence/Persistence.hx"
				return result;
			}
			else {
				#line 188 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("the specified getter has not been added")) );
			}
			
		}
		#line default
		
		public virtual string calcKey(string recordType, string operationName) {
			#line 193 "/my-component/src/persistence/Persistence.hx"
			return global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(recordType, "."), operationName);
		}
		#line default
		
		public virtual object convertToHaxe(global::maglev.MagLevAny x) {
			#line 197 "/my-component/src/persistence/Persistence.hx"
			if (( x.getType() == global::maglev.MagLevNull.getStaticType() )) {
				#line 198 "/my-component/src/persistence/Persistence.hx"
				return null;
			}
			else if (( x.getType() == global::maglev.MagLevBoolean.getStaticType() )) {
				#line 201 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevBoolean y = ((global::maglev.MagLevBoolean) (x) );
				return ((object) (y.getBool()) );
			}
			else if (( x.getType() == global::maglev.MagLevString.getStaticType() )) {
				#line 205 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevString y1 = ((global::maglev.MagLevString) (x) );
				return ((object) (y1.getString()) );
			}
			else if (( x.getType() == global::maglev.MagLevNumber.getStaticType() )) {
				#line 209 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevNumber y2 = ((global::maglev.MagLevNumber) (x) );
				return ((object) (y2.getFloat()) );
			}
			else if (( x.getType() == global::maglev.MagLevArray.getStaticType() )) {
				#line 213 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevArray y3 = ((global::maglev.MagLevArray) (x) );
				global::Array<object> arr = new global::Array<object>();
				#line 215 "/my-component/src/persistence/Persistence.hx"
				int i = 0;
				while (( i < y3.size() )) {
					#line 217 "/my-component/src/persistence/Persistence.hx"
					arr.push(this.convertToHaxe(y3.@get(i)));
					 ++ i;
				}
				
				#line 220 "/my-component/src/persistence/Persistence.hx"
				return ((object) (arr) );
			}
			else if (( x.getType() == global::maglev.MagLevObject.getStaticType() )) {
				#line 223 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevObject y4 = ((global::maglev.MagLevObject) (x) );
				global::haxe.ds.StringMap<object> map = new global::haxe.ds.StringMap<object>();
				#line 225 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevArray keys = y4.keys();
				int i1 = 0;
				#line 227 "/my-component/src/persistence/Persistence.hx"
				while (( i1 < keys.size() )) {
					#line 228 "/my-component/src/persistence/Persistence.hx"
					string key = (((global::maglev.MagLevString) (keys.@get(i1)) )).getString();
					map.@set(key, this.convertToHaxe(y4.@get(key)));
					#line 230 "/my-component/src/persistence/Persistence.hx"
					 ++ i1;
				}
				
				#line 232 "/my-component/src/persistence/Persistence.hx"
				return ((object) (map) );
			}
			else {
				#line 235 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("convertToHaxe: unknown type")) );
			}
			
		}
		#line default
		
		public virtual global::maglev.MagLevAny convertToMagLev(object x) {
			#line 240 "/my-component/src/persistence/Persistence.hx"
			if (( x == null )) {
				#line 241 "/my-component/src/persistence/Persistence.hx"
				return global::maglev.MagLevNull.create();
			}
			else if (global::Std.isOfType(((object) (x) ), ((object) (typeof(bool)) ))) {
				#line 244 "/my-component/src/persistence/Persistence.hx"
				return global::maglev.MagLevBoolean.fromBool(global::haxe.lang.Runtime.toBool(x));
			}
			else if (global::Std.isOfType(((object) (x) ), ((object) (typeof(string)) ))) {
				#line 247 "/my-component/src/persistence/Persistence.hx"
				return global::maglev.MagLevString.fromString(global::haxe.lang.Runtime.toString(x));
			}
			else if (global::Std.isOfType(((object) (x) ), ((object) (typeof(int)) ))) {
				#line 250 "/my-component/src/persistence/Persistence.hx"
				return global::maglev.MagLevNumber.fromInt(((int) (global::haxe.lang.Runtime.toInt(x)) ));
			}
			else if (global::Std.isOfType(((object) (x) ), ((object) (typeof(double)) ))) {
				#line 253 "/my-component/src/persistence/Persistence.hx"
				return global::maglev.MagLevNumber.fromFloat(((double) (global::haxe.lang.Runtime.toDouble(((object) (x) ))) ));
			}
			else if (global::Std.isOfType(((object) (x) ), ((object) (typeof(global::Array<object>)) ))) {
				#line 256 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevArray arr = global::maglev.MagLevArray.create();
				global::Array<object> y = ((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) (((object) (x) )) ))) );
				#line 258 "/my-component/src/persistence/Persistence.hx"
				{
					#line 258 "/my-component/src/persistence/Persistence.hx"
					int _g = 0;
					#line 258 "/my-component/src/persistence/Persistence.hx"
					while (( _g < y.length )) {
						#line 258 "/my-component/src/persistence/Persistence.hx"
						object item = y[_g];
						#line 258 "/my-component/src/persistence/Persistence.hx"
						 ++ _g;
						arr.push(this.convertToMagLev(item));
					}
					
				}
				
				#line 261 "/my-component/src/persistence/Persistence.hx"
				return arr;
			}
			else if (global::Std.isOfType(((object) (x) ), ((object) (typeof(global::haxe.ds.StringMap<object>)) ))) {
				#line 264 "/my-component/src/persistence/Persistence.hx"
				global::haxe.ds.StringMap<object> map = ((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((object) (x) )) ))) );
				global::maglev.MagLevObject obj = global::maglev.MagLevObject.create();
				#line 266 "/my-component/src/persistence/Persistence.hx"
				{
					#line 266 "/my-component/src/persistence/Persistence.hx"
					object key = ((object) (new global::haxe.ds._StringMap.StringMapKeyIterator<object>(((global::haxe.ds.StringMap<object>) (map) ))) );
					#line 266 "/my-component/src/persistence/Persistence.hx"
					while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(key, "hasNext", 407283053, null))) {
						#line 266 "/my-component/src/persistence/Persistence.hx"
						string key1 = global::haxe.lang.Runtime.toString(global::haxe.lang.Runtime.callField(key, "next", 1224901875, null));
						obj.@set(key1, this.convertToMagLev((map.@get(key1)).toDynamic()));
					}
					
				}
				
				#line 269 "/my-component/src/persistence/Persistence.hx"
				return obj;
			}
			else if (global::Reflect.isObject(x)) {
				#line 272 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevObject obj1 = global::maglev.MagLevObject.create();
				{
					#line 273 "/my-component/src/persistence/Persistence.hx"
					int _g1 = 0;
					#line 273 "/my-component/src/persistence/Persistence.hx"
					global::Array<string> _g2 = global::Reflect.fields(x);
					#line 273 "/my-component/src/persistence/Persistence.hx"
					while (( _g1 < _g2.length )) {
						#line 273 "/my-component/src/persistence/Persistence.hx"
						string field = _g2[_g1];
						#line 273 "/my-component/src/persistence/Persistence.hx"
						 ++ _g1;
						object val = global::Reflect.getProperty(x, field);
						#line 275 "/my-component/src/persistence/Persistence.hx"
						obj1.@set(field, this.convertToMagLev(val));
					}
					
				}
				
				#line 277 "/my-component/src/persistence/Persistence.hx"
				return obj1;
			}
			else if (( ((object) (x) ) is global::haxe.lang.Function )) {
				#line 280 "/my-component/src/persistence/Persistence.hx"
				global::haxe.lang.Function f = ((global::haxe.lang.Function) (((object) (x) )) );
				return global::maglev.MagLevFunction.fromFunction(f);
			}
			else {
				#line 284 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("convertToMagLev: unknown type")) );
			}
			
		}
		#line default
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 10 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 858513194:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						this.maglev = ((global::maglev.MagLev) (@value) );
						#line 10 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 883116808:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						this.getters = ((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (@value) ))) );
						#line 10 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 1678728017:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						this.mutators = ((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (@value) ))) );
						#line 10 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					default:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 10 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 263824376:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "convertToMagLev", 263824376)) );
					}
					
					
					case 907774356:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "convertToHaxe", 907774356)) );
					}
					
					
					case 1314583562:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "calcKey", 1314583562)) );
					}
					
					
					case 5144726:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get", 5144726)) );
					}
					
					
					case 1069478790:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "mutate", 1069478790)) );
					}
					
					
					case 1533285388:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "addGetter", 1533285388)) );
					}
					
					
					case 1860196033:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "addMutator", 1860196033)) );
					}
					
					
					case 858513194:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						return this.maglev;
					}
					
					
					case 883116808:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						return this.getters;
					}
					
					
					case 1678728017:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						return this.mutators;
					}
					
					
					default:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 10 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 263824376:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						return this.convertToMagLev(dynargs[0]);
					}
					
					
					case 907774356:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						return this.convertToHaxe(((global::maglev.MagLevAny) (dynargs[0]) ));
					}
					
					
					case 1314583562:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						return this.calcKey(global::haxe.lang.Runtime.toString(dynargs[0]), global::haxe.lang.Runtime.toString(dynargs[1]));
					}
					
					
					case 5144726:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						return this.@get(global::haxe.lang.Runtime.toString(dynargs[0]), global::haxe.lang.Runtime.toString(dynargs[1]), dynargs[2]);
					}
					
					
					case 1069478790:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						this.mutate(global::haxe.lang.Runtime.toString(dynargs[0]), global::haxe.lang.Runtime.toString(dynargs[1]), dynargs[2]);
						#line 10 "/my-component/src/persistence/Persistence.hx"
						break;
					}
					
					
					case 1533285388:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						this.addGetter(global::haxe.lang.Runtime.toString(dynargs[0]), global::haxe.lang.Runtime.toString(dynargs[1]), dynargs[2], ( (( dynargs.Length > 3 )) ? (dynargs[3]) : (null) ), ( (( dynargs.Length > 4 )) ? (dynargs[4]) : (null) ), global::haxe.lang.Null<object>.ofDynamic<bool>(( (( dynargs.Length > 5 )) ? (dynargs[5]) : (null) )));
						#line 10 "/my-component/src/persistence/Persistence.hx"
						break;
					}
					
					
					case 1860196033:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						this.addMutator(global::haxe.lang.Runtime.toString(dynargs[0]), global::haxe.lang.Runtime.toString(dynargs[1]), dynargs[2], ( (( dynargs.Length > 3 )) ? (dynargs[3]) : (null) ), global::haxe.lang.Null<object>.ofDynamic<bool>(( (( dynargs.Length > 4 )) ? (dynargs[4]) : (null) )));
						#line 10 "/my-component/src/persistence/Persistence.hx"
						break;
					}
					
					
					default:
					{
						#line 10 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				#line 10 "/my-component/src/persistence/Persistence.hx"
				return null;
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 10 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("maglev");
			#line 10 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("getters");
			#line 10 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("mutators");
			#line 10 "/my-component/src/persistence/Persistence.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_addMutator_72__Fun : global::haxe.lang.Function {
		
		public Persistence_addMutator_72__Fun() : base(1, 0) {
		}
		
		
		public static global::persistence.Persistence_addMutator_72__Fun __hx_current;
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 72 "/my-component/src/persistence/Persistence.hx"
			object v = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			#line 72 "/my-component/src/persistence/Persistence.hx"
			return v;
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_addGetter_83__Fun : global::haxe.lang.Function {
		
		public Persistence_addGetter_83__Fun() : base(1, 0) {
		}
		
		
		public static global::persistence.Persistence_addGetter_83__Fun __hx_current;
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 83 "/my-component/src/persistence/Persistence.hx"
			object v = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			#line 83 "/my-component/src/persistence/Persistence.hx"
			return v;
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence_addGetter_86__Fun : global::haxe.lang.Function {
		
		public Persistence_addGetter_86__Fun() : base(1, 0) {
		}
		
		
		public static global::persistence.Persistence_addGetter_86__Fun __hx_current;
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 86 "/my-component/src/persistence/Persistence.hx"
			object v = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			#line 86 "/my-component/src/persistence/Persistence.hx"
			return v;
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence___hx_ctor_persistence_Persistence_20__Fun : global::haxe.lang.Function {
		
		public Persistence___hx_ctor_persistence_Persistence_20__Fun(global::persistence.Persistence _gthis) : base(1, 0) {
			#line 20 "/my-component/src/persistence/Persistence.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 20 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				string recordType = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
				#line 22 "/my-component/src/persistence/Persistence.hx"
				string operationName = (((global::maglev.MagLevString) (args.@get(1)) )).getString();
				object strategyMethod = this._gthis.convertToHaxe(args.@get(2));
				#line 24 "/my-component/src/persistence/Persistence.hx"
				object updateMapper = null;
				if (( args.size() > 3 )) {
					#line 26 "/my-component/src/persistence/Persistence.hx"
					updateMapper = this._gthis.convertToHaxe(args.@get(3));
				}
				
				#line 28 "/my-component/src/persistence/Persistence.hx"
				global::haxe.lang.Null<bool> useRecordDataAsParams = default(global::haxe.lang.Null<bool>);
				if (( args.size() > 4 )) {
					#line 30 "/my-component/src/persistence/Persistence.hx"
					useRecordDataAsParams = global::haxe.lang.Null<object>.ofDynamic<bool>(((object) (this._gthis.convertToHaxe(args.@get(4))) ));
				}
				
				#line 32 "/my-component/src/persistence/Persistence.hx"
				this._gthis.addMutator(recordType, operationName, strategyMethod, updateMapper, useRecordDataAsParams);
				return global::maglev.MagLevResult.fromResult(global::maglev.MagLevBoolean.fromBool(true));
			}
			#line default
		}
		
		
		public global::persistence.Persistence _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence___hx_ctor_persistence_Persistence_35__Fun : global::haxe.lang.Function {
		
		public Persistence___hx_ctor_persistence_Persistence_35__Fun(global::persistence.Persistence _gthis) : base(1, 0) {
			#line 35 "/my-component/src/persistence/Persistence.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 35 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				string recordType = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
				#line 37 "/my-component/src/persistence/Persistence.hx"
				string operationName = (((global::maglev.MagLevString) (args.@get(1)) )).getString();
				object strategyMethod = this._gthis.convertToHaxe(args.@get(2));
				#line 39 "/my-component/src/persistence/Persistence.hx"
				object queryMapper = null;
				if (( args.size() >= 4 )) {
					#line 41 "/my-component/src/persistence/Persistence.hx"
					queryMapper = this._gthis.convertToHaxe(args.@get(3));
				}
				
				#line 43 "/my-component/src/persistence/Persistence.hx"
				object resultMapper = null;
				if (( args.size() >= 5 )) {
					#line 45 "/my-component/src/persistence/Persistence.hx"
					resultMapper = this._gthis.convertToHaxe(args.@get(4));
				}
				
				#line 47 "/my-component/src/persistence/Persistence.hx"
				global::haxe.lang.Null<bool> useQueryValuesAsParams = default(global::haxe.lang.Null<bool>);
				if (( args.size() >= 6 )) {
					#line 49 "/my-component/src/persistence/Persistence.hx"
					useQueryValuesAsParams = new global::haxe.lang.Null<bool>((((global::maglev.MagLevBoolean) (args.@get(5)) )).getBool(), true);
				}
				
				#line 51 "/my-component/src/persistence/Persistence.hx"
				this._gthis.addGetter(recordType, operationName, strategyMethod, queryMapper, resultMapper, useQueryValuesAsParams);
				return global::maglev.MagLevResult.fromResult(global::maglev.MagLevBoolean.fromBool(true));
			}
			#line default
		}
		
		
		public global::persistence.Persistence _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence___hx_ctor_persistence_Persistence_54__Fun : global::haxe.lang.Function {
		
		public Persistence___hx_ctor_persistence_Persistence_54__Fun(global::persistence.Persistence _gthis) : base(1, 0) {
			#line 54 "/my-component/src/persistence/Persistence.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 54 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				string recordType = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
				#line 56 "/my-component/src/persistence/Persistence.hx"
				string operationName = (((global::maglev.MagLevString) (args.@get(1)) )).getString();
				object recordData = this._gthis.convertToHaxe(args.@get(2));
				#line 58 "/my-component/src/persistence/Persistence.hx"
				this._gthis.mutate(recordType, operationName, recordData);
				return global::maglev.MagLevResult.fromResult(global::maglev.MagLevBoolean.fromBool(true));
			}
			#line default
		}
		
		
		public global::persistence.Persistence _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence {
	public class Persistence___hx_ctor_persistence_Persistence_61__Fun : global::haxe.lang.Function {
		
		public Persistence___hx_ctor_persistence_Persistence_61__Fun(global::persistence.Persistence _gthis) : base(1, 0) {
			#line 61 "/my-component/src/persistence/Persistence.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 61 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				string recordType = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
				#line 63 "/my-component/src/persistence/Persistence.hx"
				string operationName = (((global::maglev.MagLevString) (args.@get(1)) )).getString();
				object queryValues = this._gthis.convertToHaxe(args.@get(2));
				#line 65 "/my-component/src/persistence/Persistence.hx"
				global::maglev.MagLevAny ret = this._gthis.convertToMagLev(this._gthis.@get(recordType, operationName, queryValues));
				return global::maglev.MagLevResult.fromResult(ret);
			}
			#line default
		}
		
		
		public global::persistence.Persistence _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence._Persistence {
	public class Mutator : global::haxe.lang.HxObject {
		
		static Mutator() {
			unchecked{
				#line 293 "/my-component/src/persistence/Persistence.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{5541879, 13816588}, new string[]{"obj", "SuppressWarnings"});
				#line 293 "/my-component/src/persistence/Persistence.hx"
				{
					#line 293 "/my-component/src/persistence/Persistence.hx"
					{
						#line 293 "/my-component/src/persistence/Persistence.hx"
						object __temp_odecl1 = new global::haxe.lang.DynamicObject(new int[]{13816588}, new object[]{new global::Array<object>(new object[]{"checkstyle:FieldDocComment"})}, new int[]{}, new double[]{});
						#line 293 "/my-component/src/persistence/Persistence.hx"
						global::persistence._Persistence.Mutator.__meta__ = new global::haxe.lang.DynamicObject(new int[]{5541879}, new object[]{__temp_odecl1}, new int[]{}, new double[]{});
					}
					
				}
				
			}
		}
		#line default
		
		public Mutator(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Mutator(string recordType, object strategyMethod, object updateMapper, bool useRecordDataAsParams) {
			#line 299 "/my-component/src/persistence/Persistence.hx"
			global::persistence._Persistence.Mutator.__hx_ctor_persistence__Persistence_Mutator(this, recordType, strategyMethod, updateMapper, useRecordDataAsParams);
		}
		#line default
		
		protected static void __hx_ctor_persistence__Persistence_Mutator(global::persistence._Persistence.Mutator __hx_this, string recordType, object strategyMethod, object updateMapper, bool useRecordDataAsParams) {
			#line 300 "/my-component/src/persistence/Persistence.hx"
			if ((  ! (global::Std.isOfType(((object) (strategyMethod) ), ((object) (typeof(string)) )))  &&  ! (( ((object) (strategyMethod) ) is global::haxe.lang.Function ))  )) {
				#line 301 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("strategyMethod must be a string or function")) );
			}
			
			#line 303 "/my-component/src/persistence/Persistence.hx"
			if ((  ! (global::Std.isOfType(((object) (updateMapper) ), ((object) (typeof(string)) )))  &&  ! (( ((object) (updateMapper) ) is global::haxe.lang.Function ))  )) {
				#line 304 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("updateMapper must be a string or function")) );
			}
			
			#line 306 "/my-component/src/persistence/Persistence.hx"
			__hx_this.recordType = recordType;
			__hx_this.strategyMethod = strategyMethod;
			#line 308 "/my-component/src/persistence/Persistence.hx"
			__hx_this.updateMapper = updateMapper;
			__hx_this.useRecordDataAsParams = useRecordDataAsParams;
		}
		#line default
		
		public static object __meta__;
		
		public string recordType;
		
		public object strategyMethod;
		
		public object updateMapper;
		
		public bool useRecordDataAsParams;
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 293 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 954563242:
					{
						#line 293 "/my-component/src/persistence/Persistence.hx"
						this.updateMapper = ((object) (@value) );
						#line 293 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 1853356980:
					{
						#line 293 "/my-component/src/persistence/Persistence.hx"
						this.strategyMethod = ((object) (@value) );
						#line 293 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					default:
					{
						#line 293 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 293 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 6101114:
					{
						#line 293 "/my-component/src/persistence/Persistence.hx"
						this.useRecordDataAsParams = global::haxe.lang.Runtime.toBool(@value);
						#line 293 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 954563242:
					{
						#line 293 "/my-component/src/persistence/Persistence.hx"
						this.updateMapper = ((object) (@value) );
						#line 293 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 1853356980:
					{
						#line 293 "/my-component/src/persistence/Persistence.hx"
						this.strategyMethod = ((object) (@value) );
						#line 293 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 1633399275:
					{
						#line 293 "/my-component/src/persistence/Persistence.hx"
						this.recordType = global::haxe.lang.Runtime.toString(@value);
						#line 293 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					default:
					{
						#line 293 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 293 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 6101114:
					{
						#line 293 "/my-component/src/persistence/Persistence.hx"
						return this.useRecordDataAsParams;
					}
					
					
					case 954563242:
					{
						#line 293 "/my-component/src/persistence/Persistence.hx"
						return this.updateMapper;
					}
					
					
					case 1853356980:
					{
						#line 293 "/my-component/src/persistence/Persistence.hx"
						return this.strategyMethod;
					}
					
					
					case 1633399275:
					{
						#line 293 "/my-component/src/persistence/Persistence.hx"
						return this.recordType;
					}
					
					
					default:
					{
						#line 293 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 293 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 954563242:
					{
						#line 293 "/my-component/src/persistence/Persistence.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(this.updateMapper)) );
					}
					
					
					case 1853356980:
					{
						#line 293 "/my-component/src/persistence/Persistence.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(this.strategyMethod)) );
					}
					
					
					default:
					{
						#line 293 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 293 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("useRecordDataAsParams");
			#line 293 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("updateMapper");
			#line 293 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("strategyMethod");
			#line 293 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("recordType");
			#line 293 "/my-component/src/persistence/Persistence.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace persistence._Persistence {
	public class Getter : global::haxe.lang.HxObject {
		
		static Getter() {
			unchecked{
				#line 317 "/my-component/src/persistence/Persistence.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{5541879, 13816588}, new string[]{"obj", "SuppressWarnings"});
				#line 317 "/my-component/src/persistence/Persistence.hx"
				{
					#line 317 "/my-component/src/persistence/Persistence.hx"
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						object __temp_odecl1 = new global::haxe.lang.DynamicObject(new int[]{13816588}, new object[]{new global::Array<object>(new object[]{"checkstyle:FieldDocComment"})}, new int[]{}, new double[]{});
						#line 317 "/my-component/src/persistence/Persistence.hx"
						global::persistence._Persistence.Getter.__meta__ = new global::haxe.lang.DynamicObject(new int[]{5541879}, new object[]{__temp_odecl1}, new int[]{}, new double[]{});
					}
					
				}
				
			}
		}
		#line default
		
		public Getter(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Getter(string recordType, object strategyMethod, object queryMapper, object resultMapper, bool useQueryValuesAsParams) {
			#line 324 "/my-component/src/persistence/Persistence.hx"
			global::persistence._Persistence.Getter.__hx_ctor_persistence__Persistence_Getter(this, recordType, strategyMethod, queryMapper, resultMapper, useQueryValuesAsParams);
		}
		#line default
		
		protected static void __hx_ctor_persistence__Persistence_Getter(global::persistence._Persistence.Getter __hx_this, string recordType, object strategyMethod, object queryMapper, object resultMapper, bool useQueryValuesAsParams) {
			#line 325 "/my-component/src/persistence/Persistence.hx"
			if ((  ! (global::Std.isOfType(((object) (strategyMethod) ), ((object) (typeof(string)) )))  &&  ! (( ((object) (strategyMethod) ) is global::haxe.lang.Function ))  )) {
				#line 326 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("strategyMethod must be a string or function")) );
			}
			
			#line 328 "/my-component/src/persistence/Persistence.hx"
			if ((  ! (global::Std.isOfType(((object) (queryMapper) ), ((object) (typeof(string)) )))  &&  ! (( ((object) (queryMapper) ) is global::haxe.lang.Function ))  )) {
				#line 329 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("queryMapper must be a string or function")) );
			}
			
			#line 331 "/my-component/src/persistence/Persistence.hx"
			if ((  ! (global::Std.isOfType(((object) (resultMapper) ), ((object) (typeof(string)) )))  &&  ! (( ((object) (resultMapper) ) is global::haxe.lang.Function ))  )) {
				#line 332 "/my-component/src/persistence/Persistence.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("resultMapper must be a string or function")) );
			}
			
			#line 334 "/my-component/src/persistence/Persistence.hx"
			__hx_this.recordType = recordType;
			__hx_this.strategyMethod = strategyMethod;
			#line 336 "/my-component/src/persistence/Persistence.hx"
			__hx_this.queryMapper = queryMapper;
			__hx_this.resultMapper = resultMapper;
			#line 338 "/my-component/src/persistence/Persistence.hx"
			__hx_this.useQueryValuesAsParams = useQueryValuesAsParams;
		}
		#line default
		
		public static object __meta__;
		
		public string recordType;
		
		public object strategyMethod;
		
		public object queryMapper;
		
		public object resultMapper;
		
		public bool useQueryValuesAsParams;
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 317 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 1333802110:
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						this.resultMapper = ((object) (@value) );
						#line 317 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 189188329:
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						this.queryMapper = ((object) (@value) );
						#line 317 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 1853356980:
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						this.strategyMethod = ((object) (@value) );
						#line 317 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					default:
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 317 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 591874299:
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						this.useQueryValuesAsParams = global::haxe.lang.Runtime.toBool(@value);
						#line 317 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 1333802110:
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						this.resultMapper = ((object) (@value) );
						#line 317 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 189188329:
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						this.queryMapper = ((object) (@value) );
						#line 317 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 1853356980:
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						this.strategyMethod = ((object) (@value) );
						#line 317 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					case 1633399275:
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						this.recordType = global::haxe.lang.Runtime.toString(@value);
						#line 317 "/my-component/src/persistence/Persistence.hx"
						return @value;
					}
					
					
					default:
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 317 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 591874299:
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						return this.useQueryValuesAsParams;
					}
					
					
					case 1333802110:
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						return this.resultMapper;
					}
					
					
					case 189188329:
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						return this.queryMapper;
					}
					
					
					case 1853356980:
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						return this.strategyMethod;
					}
					
					
					case 1633399275:
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						return this.recordType;
					}
					
					
					default:
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 317 "/my-component/src/persistence/Persistence.hx"
				switch (hash) {
					case 1333802110:
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(this.resultMapper)) );
					}
					
					
					case 189188329:
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(this.queryMapper)) );
					}
					
					
					case 1853356980:
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(this.strategyMethod)) );
					}
					
					
					default:
					{
						#line 317 "/my-component/src/persistence/Persistence.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 317 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("useQueryValuesAsParams");
			#line 317 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("resultMapper");
			#line 317 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("queryMapper");
			#line 317 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("strategyMethod");
			#line 317 "/my-component/src/persistence/Persistence.hx"
			baseArr.push("recordType");
			#line 317 "/my-component/src/persistence/Persistence.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}


